### ISSUE TITLE
(Help needed!) ERROR: Error getting user details for ...

### ISSUE THREAD

**Issue by sherl0ck17** [arc298/instagram-scraper#578] opened 2020-08-27 11:38 UTC
@arc298 Hey man, I love your work and appreciate your time and effort in this project of your's, however, I do have a question. As I am new to GitHub community and was trying to understand how all this work, I have encountered this issue...

I am following a private user with my account credentials attached behind it. In case if you think I'm blocked, I am able to view that same exact user on the browser, however I am not able to download that user's posts as shown below in the picture attached. 

![Untitled](https://user-images.githubusercontent.com/65817663/91437485-8c9f1700-e89c-11ea-9e4b-e79d5a33388a.png)

Please advice me, I am at my wits' end! 

Thank you so much for your time.

**Comment by UweLau** [comment] 2020-08-28 06:47
Running also into that problem with the account of my GF. My account just works fine. Think the solution is here:

https://github.com/instaloader/instaloader/pull/785

But I do not know how to incorporate into instagram-scraper

@VasiliPupkin256 @AlexNik 
Can one of you please take a quick look at the fix for instaloader and adapt that for instagram-scraper? Would be much appreciated! :-)

**Comment by VasiliPupkin256** [comment] 2020-08-28 10:39
I can't reproduce this error and it seems that the instaloader pull request only fix some local instaloader bug. Is it specific for python3?

**Comment by UweLau** [comment] 2020-08-28 11:44
@VasiliPupkin256 I know this is only account-specific. All the symptoms described in the issue on Instaloader matches the ones sherlock and I have. It is mentioned that the answer json is different on some accounts. Maybe the json is changing gradually until all are in the new format?
How can I help you to see what json is produced with my faulty account? Is there some way I can save the json file so I can show you the differences? Thanks for you help!

**Comment by VasiliPupkin256** [comment] 2020-08-28 12:06
There was a similar issue #515 where the reporter profile wasn't provided with any json data. Try to open the userpage in the browser open page source code and look for "entry_data". Do you have any meaningful json in the field? There should be "profile_pic_url" etc.

**Comment by UweLau** [comment] 2020-08-28 12:31
@VasiliPupkin256 

The "wrong" one starts with

`"entry_data":{"ProfilePage":[{}]},"hostname":"www.instagram.com","is_whitelisted_crawl_bot":false,"deployment_stage":"c2","platform":"web",...."`

where the one that works starts with

`"entry_data":{"ProfilePage":[{"logging_page_id":"profilePage_40366806212","show_suggested_profiles":false,"show_follow_dialog":false,"graphql":{"user":{"biography":..."`

These informations are also in the "wrong" one but they are in an extra <script>:

`<script type="text/javascript">window.__initialDataLoaded(window._sharedData);</script><script type="text/javascript">window.__additionalDataLoaded('/nayeli_rose_/',{"logging_page_id":"profilePage_40366806212","show_suggested_profiles":false,"show_follow_dialog":false,"graphql":{"user":{"biography":..."`

So it seems if ProfilePage is [{}]} instead of some informations the real data is in the "additionalDataLoaded" section of the next script?

**Comment by VasiliPupkin256** [comment] 2020-08-28 12:50
So the same data is still there but in a different place? Then the pull request of instaloader makes sense. The heuristic is based on `get_shared_data` function which is called in two places where it should be fixed. Download both pages into separate text files and either fix it yourself or post here... I am not sure if there is a private data, passwords or cookies in there, be careful.

**Comment by UweLau** [comment] 2020-08-28 13:19
Sorry, I am not sure what you mean. I downloaded the source pages but they are 122k each so I can not post them here. What information do you need exactly? Sorry, I am not able to fix it myself ...

**Comment by UweLau** [comment] 2020-08-28 13:40
I could debug it with the two accounts. Take your best guess and I can tell you what happens.

**Comment by VasiliPupkin256** [comment] 2020-08-28 13:44
Ok I'll try to make a patch today or tomorrow if no one fix it earlier and will post it here

**Comment by UweLau** [comment] 2020-08-28 13:51
Thanks!

**Comment by sherl0ck17** [comment] 2020-08-29 09:53
@UweLau Thank you for your constant following up with @VasiliPupkin256, honestly wish I can help but I do not know a single thing going on in the back end!

@VasiliPupkin256 Thank you for your time in helping us debug this issue! After the issue has been fixed, will you be doing a pull request with the master folder or I should be cloning the one from instaloader instead?

**Comment by sherl0ck17** [comment] 2020-08-29 09:54
@UweLau Thank you for your constant following up with @VasiliPupkin256, honestly wish I could help but I do not understand and know a single thing that's going on in the back end!

@VasiliPupkin256 Thank you for your time in helping us debug this issue! After the issue has been fixed, will you be doing a pull request with the master folder or I should be cloning the one from instaloader instead?

**Comment by sherl0ck17** [comment] 2020-08-29 09:58
To add on onto my issue, the account of mine that is that is trying to scrape, isn't able to search for any user on Instagram, e.g., 'justin'.

![image](https://user-images.githubusercontent.com/65817663/91634205-327b8e80-ea21-11ea-9439-8ef86fdb60c0.png)

**Comment by UweLau** [comment] 2020-08-29 10:35
@sherl0ck17 I cannot confirm that for me. In the browser both my accounts work fine. It is only with instagram-scraper or instaloader where it does not work.

**Comment by VasiliPupkin256** [comment] 2020-08-29 17:12
Check the latest pull request. Does it solve the issue or not?

**Comment by UweLau** [comment] 2020-08-29 17:58
@VasiliPupkin256 I just tested the pull request and it looks very good. Only tested it with the faulty account right now but I assume you already checked for regression with your account? Username is recognized again and all is fine again! Many thanks for your speedy work.

**Comment by UweLau** [comment] 2020-08-29 19:25
@VasiliPupkin256
I am afraid there is some problem with the pull request. I have several profiles I get not the files I expect. 
entry_data and additionaldata is the same as the ones that work, at least it looks like it without checking everything

Here is a except of the screen output:
```
Searching nikkibits007 for stories: 0 media [00:00, ? media/s]
Searching nikkibits007 for stories: 0 media [00:00, ? media/s]
Searching nikkibits007 for posts: 0 media [00:03, ? media/s]
Searching jewelstaite for stories: 100%|##########| 219/219 [00:00<00:00, 77988.84 media/s]
Searching jewelstaite for stories: 0 media [00:00, ? media/s]
Searching jewelstaite for posts: 2 media [00:03,  1.61s/ media]
Downloading: 100%|##########| 5/5 [00:00<00:00, 25.73it/s]
Searching lisaharnois for stories: 0 media [00:00, ? media/s]
Searching lisaharnois for stories: 0 media [00:00, ? media/s]
Searching lisaharnois for posts: 0 media [00:00, ? media/s]
Searching mileycyrus for stories: 100%|##########| 17/17 [00:00<00:00, 16008.79 media/s]
Searching mileycyrus for stories: 0 media [00:00, ? media/s]
Searching mileycyrus for posts: 3 media [00:47, 15.95s/ media]
Downloading: 100%|##########| 8/8 [00:00<00:00, 18.31it/s]

```
Something is odd here, it does not even create the directory for profile (the ones where there is no "Downloading: 100%")

I have others where it only creates a json file (downloading metadata):

```
Searching annakournikova for stories: 100%|##########| 17/17 [00:00<00:00, 59717.90 media/s]
Searching annakournikova for stories: 0 media [00:00, ? media/s]
Searching annakournikova for posts: 0 media [00:12, ? media/s]

```
Any idea what could be wrong here?

**Comment by VasiliPupkin256** [comment] 2020-08-29 21:27
I've noted this changes in the master branch yes. Something has changed from the latest release in the code.. but it seems to work fine just donwloading is not printed if all the files were already fetched to this point.

Does this problem only occur on the "faulty" profile which is getting new data format from Instagram or is this the same for an old one too?

**Comment by UweLau** [comment] 2020-08-30 09:55
@VasiliPupkin256 You are right. The changes were presumable made in April. I still used a modified build from February so it behaved differently. I had to update to apply your pull request so I got these changes too. 
Your changes worked with both the old style data_entry and the new additionalData style

**Comment by VasiliPupkin256** [comment] 2020-08-30 16:28
So there is a bug from april and it doesn't download some profiles?

**Comment by UweLau** [comment] 2020-08-31 07:16
I am not sure it is a bug. The files missing are only profile pictures which were already downloaded. I was using the latest option. It seems, it does not download anything if there is not also a post or story to download. But I am not sure how the case would be handled if only the profile picture changes and there is nothing further to download. Because the profile pictures are all October 2010 timestamp I think and in the latest file there is the last Epoch time stamp somewhere in August 2020 ...

**Comment by sherl0ck17** [comment] 2020-09-02 07:19
@UweLau Hi, just to check does this script not download the highest quality available for the posts? 

@VasiliPupkin256 Just to check should I be removing my old file and cloning your committed files instead? I not too sure how to move on from here. Please help me, thank you.

**Comment by VasiliPupkin256** [comment] 2020-09-02 13:00
Yes, update to the latest version `pip install --upgrade instagram-scraper` and then substitute the app.py file somewhere in the Lib\site-packages\instagram_scraper\ in your python directory, or the other way depending on how you've installed the scraper

**Comment by sherl0ck17** [comment] 2020-09-03 09:45
> Yes, update to the latest version `pip install --upgrade instagram-scraper` and then substitute the app.py file somewhere in the Lib\site-packages\instagram_scraper\ in your python directory, or the other way depending on how you've installed the scraper

@VasiliPupkin256 I ran this `pip install --upgrade instagram-scraper` command and had replaced my app.py in the directory I've installed the scraper at. 

I tried to type the same command (start of the thread) but this time without my username and password but it showed this error, am I doing it wrongly? Or what should the correct command be used to invoke the kind of response I am looking for? 

Please continue to assist me. 

![Capture](https://user-images.githubusercontent.com/65817663/92099102-b01e1080-ee0c-11ea-9594-eeef9a85f6eb.PNG)

**Comment by sherl0ck17** [comment] 2020-09-03 09:49
@VasiliPupkin256 I ran this command `pip install --upgrade instagram-scraper` and had replaced my app.py in the directory I've installed the scraper at.

I tried to type the same command (start of the thread) but this time without my username and password but it showed this error, am I doing it wrongly? Or what should the correct command be used to invoke the kind of response I am looking for?

![Capture](https://user-images.githubusercontent.com/65817663/92099734-74d01180-ee0d-11ea-873d-f88834723919.PNG)

Please continue to assist me.

**Comment by VasiliPupkin256** [comment] 2020-09-03 20:12
No no, you should overwrite the app.py file in the folder where the scraper is installed by pip, it is somewhere under the python dir depending on the OS. And then you run scraper the same way as usual.

**Comment by sherl0ck17** [comment] 2020-09-04 04:50
> No no, you should overwrite the app.py file in the folder where the scraper is installed by pip, it is somewhere under the python dir depending on the OS. And then you run scraper the same way as usual.

@VasiliPupkin256 Just checking with you, why doesn't replacing the app.py in the directory I've installed the scraper at fix the job?

Right now, I have a few app.py files - 
app.py inside `python\3.8.3\Lib\site-packages\instagram_scraper-1.8.1-py3.8.egg\instagram_scraper` and app.py & app2.py inside `python\3.8.3\Lib\site-packages\instagram_scraper`

Please advice me which do I replace and/or delete?

**Comment by VasiliPupkin256** [comment] 2020-09-04 09:33
It fixes. But then you've run the strange command `python3 app.py` instead of just running `instagram-scraper` from the command line.

**Comment by UweLau** [comment] 2020-09-05 15:20
@sherl0ck17  Sorry for not answering earlier. I do not know if instagram-scraper gets the highest resolution file avaialable. Maybe @VasiliPupkin256 can shed some more light on that issue. I really do not know if there are higher resolutions available ...

**Comment by sherl0ck17** [comment] 2020-09-06 10:41
> It fixes. But then you've run the strange command `python3 app.py` instead of just running `instagram-scraper` from the command line.

@VasiliPupkin256 Right now, I'm running your codes and tried running the `instagram-scraper` method but it's still not working. It only downloads the user's profile picture but **not** all the other picture posts despite being his followers. Both picture are scraping from the exact same user.
![Capture1](https://user-images.githubusercontent.com/65817663/92323436-49e2f900-f06b-11ea-8ede-fa14d3209071.PNG)

Back to the strange command of `python3 app.py`, is there anything I have to fill it up?
![Capture](https://user-images.githubusercontent.com/65817663/92323463-7860d400-f06b-11ea-9923-fb3f67e398ab.PNG)

Please continue to further advice me, it's so difficult to get this to work!

**Comment by sherl0ck17** [comment] 2020-09-06 10:45
> @sherl0ck17 Sorry for not answering earlier. I do not know if instagram-scraper gets the highest resolution file avaialable. Maybe @VasiliPupkin256 can shed some more light on that issue. I really do not know if there are higher resolutions available ...

@UweLau Hi, can you take a screenshot of the command you run on a private user with your credentials all blocked out, just like what I've done? It would be good for me to have a look!
@VasiliPupkin256 Yes please do shed some light on it! Cause I went to compare the picture size (downloaded manually) vs the picture which was scraped on a public user was different, so I would assume that the resolution will be different too?

**Comment by sherl0ck17** [comment] 2020-09-06 10:46
> @sherl0ck17 Sorry for not answering earlier. I do not know if instagram-scraper gets the highest resolution file avaialable. Maybe @VasiliPupkin256 can shed some more light on that issue. I really do not know if there are higher resolutions available ...

@UweLau Hi, can you take a screenshot of the command you run on a private user with your credentials all blocked out, just like what I've done? It would be good for me to have a look!

@VasiliPupkin256 Yes please do shed some light on it! Cause I went to compare the picture size (downloaded manually) vs the picture which was scraped on a public user was different, so I would assume that the resolution will be different too?

**Comment by VasiliPupkin256** [comment] 2020-09-06 12:12
@sherl0ck17 just to make sure that you've changed the right `app.py` file please add the debug print to it, open it in editor find the __init__ function definition and add `print(..)` statement to its first line. Something like this

    def __init__(self, **kwargs):
        print("Hello world")
        default_attr =  ...
        ...

and then run the instagram scraper again.

@UweLau no it is **not always** in the highest resolution available. We can't strip filters from the url and only instagram knows why and when it returns one resolution or the other. Probably it depends on the user agent provided and the screen size of a device. Sometimes it is in the highest resolution sometimes not.

**Comment by sherl0ck17** [comment] 2020-09-06 13:04
> @sherl0ck17 just to make sure that you've changed the right `app.py` file please add the debug print to it, open it in editor find the **init** function definition and add `print(..)` statement to its first line. Something like this
> 
> ```
> def __init__(self, **kwargs):
>     print("Hello world")
>     default_attr =  ...
>     ...
> ```
> 
> and then run the instagram scraper again.
> 
@VasiliPupkin256 Yeap, I git cloned your files under 'New Folder' as seen in the picture.

Two different commands with two different results.
![Capture](https://user-images.githubusercontent.com/65817663/92326186-e95fb600-f082-11ea-94a5-45af7fbdf8d0.PNG)
![Capture](https://user-images.githubusercontent.com/65817663/92326387-4740cd80-f084-11ea-853b-eedf104d81ea.PNG)

Files inside path.

![image](https://user-images.githubusercontent.com/65817663/92326241-62f7a400-f083-11ea-8359-dcdbda4216b6.png)

![image](https://user-images.githubusercontent.com/65817663/92326282-8c183480-f083-11ea-88cc-7235a070dfc8.png)

The difference between the old folder and the new one was that the old folder had 'instagram_scraper.egg-info' while the cloned files did not have any.

**Comment by VasiliPupkin256** [comment] 2020-09-06 13:12
Why are you running `python3 app.py`??? I don't get it. Ok. I don't know how you are running the scraper. If you are running it the usual way my instructions should've worked. If you are running it as a developer then you would probably know which file is executed and I can't help you.

The error `inconsistent use tabs and spaces in indentation` means you've mixed spaces and tabs in indention before the `print("Hellow world")` statement. There should be only spaces and no tabs. But again, I don't know what editor you are using, you should know it better.

**Comment by sherl0ck17** [comment] 2020-09-06 13:43
> Why are you running `python3 app.py`??? I don't get it. Ok. I don't know how you are running the scraper. If you are running it the usual way my instructions should've worked. If you are running it as a developer then you would probably know which file is executed and I can't help you.
> 
> The error `inconsistent use tabs and spaces in indentation` means you've mixed spaces and tabs in indention before the `print("Hellow world")` statement. There should be only spaces and no tabs. But again, I don't know what editor you are using, you should know it better.

The reason why I ran the old command is to show you that I've added the codes you wanted it to show which therefore does reflect them. However with your command, the error still exist 'ERROR: Error getting user details for ***. Please verify that the user exists.'. I've copied and paste what you wrote. Do advice me on it, I'm not too sure the syntax of using python & I'm using notepad++. Can you help to check the files inside the folders, are they the same as your's too? 

Btw, is there a way whereby I am able to email you for real time updates?

**Comment by VasiliPupkin256** [comment] 2020-09-06 15:50
In notedap++ open the app.py you've replaced with the new one, find the line with "Hello world" and change tabs to spaces in the beginning of it

**Comment by sherl0ck17** [comment] 2020-09-08 09:49
> In notedap++ open the app.py you've replaced with the new one, find the line with "Hello world" and change tabs to spaces in the beginning of it

This is the new app.py, did you meant it like this?

![image](https://user-images.githubusercontent.com/65817663/92460993-42525a00-f1fb-11ea-89d0-2dc7db55fb3f.png)

**Comment by VasiliPupkin256** [comment] 2020-09-08 10:14
I've told you to change tabs to spaces, but you removed them.

You are a programmer. You know how to clone repos and start python programs from console. Maybe someone else wants to play a support and help a user who is actually a programmer intentionally making mistakes and getting into trouble, or you can just wait for the pull request to be merged and a new version is released.

**Comment by sherl0ck17** [comment] 2020-09-08 12:18
> I've told you to change tabs to spaces, but you removed them.
> 
> You are a programmer. You know how to clone repos and start python programs from console. Maybe someone else wants to play a support and help a user who is actually a programmer intentionally making mistakes and getting into trouble, or you can just wait for the pull request to be merged and a new version is released.

I honestly do not understand what you're trying to convey. I am not as experienced as you think I am, which is why I am reaching out asking for your help. 

Can you take a screenshot of what you meant instead of getting mad at the things I've done?

Thank you.

**Comment by sherl0ck17** [comment] 2020-09-13 14:37
> I've told you to change tabs to spaces, but you removed them.
> 
> You are a programmer. You know how to clone repos and start python programs from console. Maybe someone else wants to play a support and help a user who is actually a programmer intentionally making mistakes and getting into trouble, or you can just wait for the pull request to be merged and a new version is released.

@VasiliPupkin256 Thanks so much for your help and input! 

Anyone who is able to give an actual CONSTRUCTIVE FEEDBACK on my issue is welcome!

**Comment by AlexNik** [comment] 2020-09-13 18:11
@sherl0ck17 what's your problem now?

**Comment by sherl0ck17** [comment] 2020-09-13 18:37
> @sherl0ck17 what's your problem now?

If you were to read the thread above, you should know that I am unable to run the code as intended.

**Comment by AlexNik** [comment] 2020-09-14 11:07
@sherl0ck17 I see but you do a lot of things in this issue.
I don't know how to help you if you don't say in what state you are.

From screens above I would recommend this in PowerShell
CAUTION: It will break all yours changes
Change `****` to your credentials.
```
cd D:\V\InstaStoriesAPI\instagram-scraper\instagram_scraper
git fetch --all
git reset --hard origin/master
python3 app.py ****
```

**Closed** 2020-10-10 16:22 UTC
