### ISSUE TITLE
This is not a issue

### ISSUE THREAD

**Issue by ecoli404** [arc298/instagram-scraper#291] opened 2018-09-09 22:49 UTC
I love your app, and there are now some new media called Highlights. While looking up, I've found every media is contained over: "/stories/highlights", and I thing it could be easy to implement in your code, but I'm really new over this and I don't know what to do. Thanks!

**Comment by edgartaor** [comment] 2018-09-09 23:05
Seem this already was sugested #261 .
But I don't know if there is a milestone for this feature.

**Comment by aaronraimist** [comment] 2019-01-01 03:17
Duplicate of #147

**Comment by AlexNik** [comment] 2021-05-26 21:27
Done in #481

**Closed by AlexNik** 2021-05-26 21:27 UTC
