### ISSUE TITLE
Feature request #2: Story Highlights

### ISSUE THREAD

**Issue by thewracl** [arc298/instagram-scraper#261] opened 2018-07-13 07:57 UTC
@rarcega @VasiliPupkin256 
A while ago, Instagram added that feature to show "Story Highlights" if the user wishes that. They are shown on the web page above the pictures:
See here for an example: https://www.instagram.com/bellathorne/

It would be great, if one could get all the pictures/movies behind the Story Highlights, f.e. "Number 4 ...", "Number 2 ..." or "Holy eff". Don't know if the Story Highlights are accessible through API calls or if a web page scraping would be the easier way (Though I can't find any of th words, f.e. Holy in the webpage source)

As all the media for this feature a older story media it would be best to just safe them along the other pictures/movies in the base folder.

**Comment by aaronraimist** [comment] 2019-01-01 03:17
Duplicate of #147

**Comment by AlexNik** [comment] 2021-05-26 21:27
Done in #481

**Closed by AlexNik** 2021-05-26 21:27 UTC
Labels: enhancement, feature request
